### ISSUE TITLE
Run EC predictions on new molecules

### ISSUE THREAD

**Issue by miquelduranfrigola** [HassounLab/Boost-RS#1]
Hello!
Thanks for a great repository.
I wonder if there is any script available to run EC-substrate predictions on a given molecule. Also, I'd like to know if pre-trained models are available.
Many thanks!
M

**Comment by xinmengli** [comment]
Hi M, 

Thank you for being interested! This is work currently under review. We will add more functionalities as this review process needs.
Back to your question, while the current version we have is an end-to-end model and **does not** yet include the version for the cold start problem (prediction for new molecules unseen in the training set).

Thanks, Xinmeng

**Comment by miquelduranfrigola** [comment]
Dear Xinmeng,
Thanks for your prompt reply. I will wait until the work is published, hopefully with a few updates! Also, thanks for clarifying that currently a version for the cold start problem is not available.
Best,
Miquel

**Comment by xinmengli** [comment]
I will close the issue for now (till the paper published) and feel free to reopen it.
