### ISSUE TITLE
Inquiry: Downloading Dataset for Research Interest

### ISSUE THREAD

**Issue by Tigter** [HassounLab/Boost-RS#2]
Hi！
I am highly interested in your research work. Your project seems to align perfectly with my area of study, and I would like to delve deeper into it.
I noticed that your repository contains a dataset that is crucial. I would be grateful if you could kindly provide guidance on how to download the dataset associated with your project.

**Comment by LdxxdL** [comment]
I'm having the same problem now. have you already got the dataset?
@Tigter

**Comment by LdxxdL** [comment]
@Tigter 
I find the link https://tufts.box.com/s/tc46ue1d05yyvhk3z486nuklokk35hug in the commit history, which contains the dataset.
The author may delete it by mistake.

**Comment by xinmengli** [comment]
Thanks @Tigter and @LdxxdL  for your interest
Thank you @LdxxdL for pointing this out, it is the right link. I added the link back
